services:
  fast-api-app:
    build: .
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "33306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:

